/* THIS FILE IS AUTO-GENERATED BY tools/generate-geojson-registry.ts */
/* Do not edit by hand. */

import { ManifestFileEnrty } from "./Manifest/manifestType";
import data_address from "@/assets/imdf/address.geojson";
import data_interact_buildings_buildings from "@/assets/imdf/interact/buildings/buildings.geojson";
import data_interact_footprints_footprints from "@/assets/imdf/interact/footprints/footprints.geojson";
import data_studyhall_buildings_buildings from "@/assets/imdf/studyhall/buildings/buildings.geojson";
import data_studyhall_footprints_footprint from "@/assets/imdf/studyhall/footprints/footprint.geojson";
import data_studyhall_levels_floor1 from "@/assets/imdf/studyhall/levels/floor1.geojson";
import data_studyhall_levels_floor2 from "@/assets/imdf/studyhall/levels/floor2.geojson";
import data_studyhall_levels_floor3 from "@/assets/imdf/studyhall/levels/floor3.geojson";
import data_studyhall_levels_floor4 from "@/assets/imdf/studyhall/levels/floor4.geojson";
import data_studyhall_levels_floor5 from "@/assets/imdf/studyhall/levels/floor5.geojson";
import data_studyhall_sections_floor1 from "@/assets/imdf/studyhall/sections/floor1.geojson";
import data_studyhall_sections_floor2 from "@/assets/imdf/studyhall/sections/floor2.geojson";
import data_studyhall_sections_floor3 from "@/assets/imdf/studyhall/sections/floor3.geojson";
import data_studyhall_sections_floor4 from "@/assets/imdf/studyhall/sections/floor4.geojson";
import data_studyhall_sections_floor5 from "@/assets/imdf/studyhall/sections/floor5.geojson";
import data_studyhall_units_floor1 from "@/assets/imdf/studyhall/units/floor1.geojson";
import data_studyhall_units_floor2 from "@/assets/imdf/studyhall/units/floor2.geojson";
import data_studyhall_units_floor3 from "@/assets/imdf/studyhall/units/floor3.geojson";
import data_studyhall_units_floor4 from "@/assets/imdf/studyhall/units/floor4.geojson";
import data_studyhall_units_floor5 from "@/assets/imdf/studyhall/units/floor5.geojson";
import data_studyhall_units_stairs from "@/assets/imdf/studyhall/units/stairs.geojson";
import data_venue_venue from "@/assets/imdf/venue/venue.geojson";

export const geoJsonMap: Record<string, ManifestFileEnrty & { content?: any }> = {
  address: {
    logicalId: "address",
    relativePath: "address.geojson",
    version: "1.0.0",
    size: 294,
    content: data_address,
  },
  interact_buildings_buildings: {
    logicalId: "interact_buildings_buildings",
    relativePath: "interact/buildings/buildings.geojson",
    version: "1.0.0",
    size: 413,
    content: data_interact_buildings_buildings,
  },
  interact_footprints_footprints: {
    logicalId: "interact_footprints_footprints",
    relativePath: "interact/footprints/footprints.geojson",
    version: "1.0.0",
    size: 496,
    content: data_interact_footprints_footprints,
  },
  studyhall_buildings_buildings: {
    logicalId: "studyhall_buildings_buildings",
    relativePath: "studyhall/buildings/buildings.geojson",
    version: "1.0.0",
    size: 411,
    content: data_studyhall_buildings_buildings,
  },
  studyhall_footprints_footprint: {
    logicalId: "studyhall_footprints_footprint",
    relativePath: "studyhall/footprints/footprint.geojson",
    version: "1.0.0",
    size: 999,
    content: data_studyhall_footprints_footprint,
  },
  studyhall_levels_floor1: {
    logicalId: "studyhall_levels_floor1",
    relativePath: "studyhall/levels/floor1.geojson",
    version: "1.0.0",
    size: 1209,
    content: data_studyhall_levels_floor1,
  },
  studyhall_levels_floor2: {
    logicalId: "studyhall_levels_floor2",
    relativePath: "studyhall/levels/floor2.geojson",
    version: "1.0.0",
    size: 1209,
    content: data_studyhall_levels_floor2,
  },
  studyhall_levels_floor3: {
    logicalId: "studyhall_levels_floor3",
    relativePath: "studyhall/levels/floor3.geojson",
    version: "1.0.0",
    size: 1209,
    content: data_studyhall_levels_floor3,
  },
  studyhall_levels_floor4: {
    logicalId: "studyhall_levels_floor4",
    relativePath: "studyhall/levels/floor4.geojson",
    version: "1.0.0",
    size: 701,
    content: data_studyhall_levels_floor4,
  },
  studyhall_levels_floor5: {
    logicalId: "studyhall_levels_floor5",
    relativePath: "studyhall/levels/floor5.geojson",
    version: "1.0.0",
    size: 701,
    content: data_studyhall_levels_floor5,
  },
  studyhall_sections_floor1: {
    logicalId: "studyhall_sections_floor1",
    relativePath: "studyhall/sections/floor1.geojson",
    version: "1.0.0",
    size: 4992,
    content: data_studyhall_sections_floor1,
  },
  studyhall_sections_floor2: {
    logicalId: "studyhall_sections_floor2",
    relativePath: "studyhall/sections/floor2.geojson",
    version: "1.0.0",
    size: 8857,
    content: data_studyhall_sections_floor2,
  },
  studyhall_sections_floor3: {
    logicalId: "studyhall_sections_floor3",
    relativePath: "studyhall/sections/floor3.geojson",
    version: "1.0.0",
    size: 8037,
    content: data_studyhall_sections_floor3,
  },
  studyhall_sections_floor4: {
    logicalId: "studyhall_sections_floor4",
    relativePath: "studyhall/sections/floor4.geojson",
    version: "1.0.0",
    size: 2312,
    content: data_studyhall_sections_floor4,
  },
  studyhall_sections_floor5: {
    logicalId: "studyhall_sections_floor5",
    relativePath: "studyhall/sections/floor5.geojson",
    version: "1.0.0",
    size: 2578,
    content: data_studyhall_sections_floor5,
  },
  studyhall_units_floor1: {
    logicalId: "studyhall_units_floor1",
    relativePath: "studyhall/units/floor1.geojson",
    version: "1.0.0",
    size: 52459,
    content: data_studyhall_units_floor1,
  },
  studyhall_units_floor2: {
    logicalId: "studyhall_units_floor2",
    relativePath: "studyhall/units/floor2.geojson",
    version: "1.0.0",
    size: 57712,
    content: data_studyhall_units_floor2,
  },
  studyhall_units_floor3: {
    logicalId: "studyhall_units_floor3",
    relativePath: "studyhall/units/floor3.geojson",
    version: "1.0.0",
    size: 59229,
    content: data_studyhall_units_floor3,
  },
  studyhall_units_floor4: {
    logicalId: "studyhall_units_floor4",
    relativePath: "studyhall/units/floor4.geojson",
    version: "1.0.0",
    size: 20681,
    content: data_studyhall_units_floor4,
  },
  studyhall_units_floor5: {
    logicalId: "studyhall_units_floor5",
    relativePath: "studyhall/units/floor5.geojson",
    version: "1.0.0",
    size: 25372,
    content: data_studyhall_units_floor5,
  },
  studyhall_units_stairs: {
    logicalId: "studyhall_units_stairs",
    relativePath: "studyhall/units/stairs.geojson",
    version: "1.0.0",
    size: 40639,
    content: data_studyhall_units_stairs,
  },
  venue_venue: {
    logicalId: "venue_venue",
    relativePath: "venue/venue.geojson",
    version: "1.0.0",
    size: 976,
    content: data_venue_venue,
  },
};

export default geoJsonMap;