/* THIS FILE IS AUTO-GENERATED BY scripts/generate-geojson-registry.js */
/* Do not edit by hand. */

import { Feature, FeatureCollection, Geometry } from "geojson"

import address from "@/assets/data/imdf/address.json";
import interact_footprint from "@/assets/data/imdf/interact/footprint.json";
import interact_levels_floor1 from "@/assets/data/imdf/interact/levels/floor1.json";
import interact_levels_floor2 from "@/assets/data/imdf/interact/levels/floor2.json";
import interact_units_floor1 from "@/assets/data/imdf/interact/units/floor1.json";
import interact_units_floor2 from "@/assets/data/imdf/interact/units/floor2.json";
import interact_units_floor3 from "@/assets/data/imdf/interact/units/floor3.json";
import studyhall_footprint from "@/assets/data/imdf/studyhall/footprint.json";
import studyhall_levels_floor1_3 from "@/assets/data/imdf/studyhall/levels/floor1$3.json";
import studyhall_levels_floor4_5 from "@/assets/data/imdf/studyhall/levels/floor4$5.json";
import studyhall_sections_floor1 from "@/assets/data/imdf/studyhall/sections/floor1.json";
import studyhall_sections_floor2 from "@/assets/data/imdf/studyhall/sections/floor2.json";
import studyhall_sections_floor3 from "@/assets/data/imdf/studyhall/sections/floor3.json";
import studyhall_sections_floor4 from "@/assets/data/imdf/studyhall/sections/floor4.json";
import studyhall_sections_floor5 from "@/assets/data/imdf/studyhall/sections/floor5.json";
import studyhall_stairs from "@/assets/data/imdf/studyhall/stairs.json";
import studyhall_units_floor1 from "@/assets/data/imdf/studyhall/units/floor1.json";
import studyhall_units_floor2 from "@/assets/data/imdf/studyhall/units/floor2.json";
import studyhall_units_floor3 from "@/assets/data/imdf/studyhall/units/floor3.json";
import studyhall_units_floor4 from "@/assets/data/imdf/studyhall/units/floor4.json";
import studyhall_units_floor5 from "@/assets/data/imdf/studyhall/units/floor5.json";
import venue_venue from "@/assets/data/imdf/venue/venue.json";

export const geoJsonMap = {
  address: {
    logicalId: "address",
    relativePath: "data/imdf/address.json",
    content: address as Feature<Geometry | null>,
  },
  interact_footprint: {
    logicalId: "interact_footprint",
    relativePath: "data/imdf/interact/footprint.json",
    content: interact_footprint as FeatureCollection,
  },
  interact_levels_floor1: {
    logicalId: "interact_levels_floor1",
    relativePath: "data/imdf/interact/levels/floor1.json",
    content: interact_levels_floor1 as FeatureCollection,
  },
  interact_levels_floor2: {
    logicalId: "interact_levels_floor2",
    relativePath: "data/imdf/interact/levels/floor2.json",
    content: interact_levels_floor2 as FeatureCollection,
  },
  interact_units_floor1: {
    logicalId: "interact_units_floor1",
    relativePath: "data/imdf/interact/units/floor1.json",
    content: interact_units_floor1 as FeatureCollection,
  },
  interact_units_floor2: {
    logicalId: "interact_units_floor2",
    relativePath: "data/imdf/interact/units/floor2.json",
    content: interact_units_floor2 as FeatureCollection,
  },
  interact_units_floor3: {
    logicalId: "interact_units_floor3",
    relativePath: "data/imdf/interact/units/floor3.json",
    content: interact_units_floor3 as FeatureCollection,
  },
  studyhall_footprint: {
    logicalId: "studyhall_footprint",
    relativePath: "data/imdf/studyhall/footprint.json",
    content: studyhall_footprint as FeatureCollection,
  },
  studyhall_levels_floor1$3: {
    logicalId: "studyhall_levels_floor1$3",
    relativePath: "data/imdf/studyhall/levels/floor1$3.json",
    content: studyhall_levels_floor1_3 as FeatureCollection,
  },
  studyhall_levels_floor4$5: {
    logicalId: "studyhall_levels_floor4$5",
    relativePath: "data/imdf/studyhall/levels/floor4$5.json",
    content: studyhall_levels_floor4_5 as FeatureCollection,
  },
  studyhall_sections_floor1: {
    logicalId: "studyhall_sections_floor1",
    relativePath: "data/imdf/studyhall/sections/floor1.json",
    content: studyhall_sections_floor1 as FeatureCollection,
  },
  studyhall_sections_floor2: {
    logicalId: "studyhall_sections_floor2",
    relativePath: "data/imdf/studyhall/sections/floor2.json",
    content: studyhall_sections_floor2 as FeatureCollection,
  },
  studyhall_sections_floor3: {
    logicalId: "studyhall_sections_floor3",
    relativePath: "data/imdf/studyhall/sections/floor3.json",
    content: studyhall_sections_floor3 as FeatureCollection,
  },
  studyhall_sections_floor4: {
    logicalId: "studyhall_sections_floor4",
    relativePath: "data/imdf/studyhall/sections/floor4.json",
    content: studyhall_sections_floor4 as FeatureCollection,
  },
  studyhall_sections_floor5: {
    logicalId: "studyhall_sections_floor5",
    relativePath: "data/imdf/studyhall/sections/floor5.json",
    content: studyhall_sections_floor5 as FeatureCollection,
  },
  studyhall_stairs: {
    logicalId: "studyhall_stairs",
    relativePath: "data/imdf/studyhall/stairs.json",
    content: studyhall_stairs as FeatureCollection,
  },
  studyhall_units_floor1: {
    logicalId: "studyhall_units_floor1",
    relativePath: "data/imdf/studyhall/units/floor1.json",
    content: studyhall_units_floor1 as FeatureCollection,
  },
  studyhall_units_floor2: {
    logicalId: "studyhall_units_floor2",
    relativePath: "data/imdf/studyhall/units/floor2.json",
    content: studyhall_units_floor2 as FeatureCollection,
  },
  studyhall_units_floor3: {
    logicalId: "studyhall_units_floor3",
    relativePath: "data/imdf/studyhall/units/floor3.json",
    content: studyhall_units_floor3 as FeatureCollection,
  },
  studyhall_units_floor4: {
    logicalId: "studyhall_units_floor4",
    relativePath: "data/imdf/studyhall/units/floor4.json",
    content: studyhall_units_floor4 as FeatureCollection,
  },
  studyhall_units_floor5: {
    logicalId: "studyhall_units_floor5",
    relativePath: "data/imdf/studyhall/units/floor5.json",
    content: studyhall_units_floor5 as FeatureCollection,
  },
  venue_venue: {
    logicalId: "venue_venue",
    relativePath: "data/imdf/venue/venue.json",
    content: venue_venue as FeatureCollection,
  },
};

export default geoJsonMap;

// オブジェクトのunion型定義
export type MapId = keyof typeof geoJsonMap;