/* THIS FILE IS AUTO-GENERATED BY tools/generate-geojson-registry.js */
/* Do not edit by hand. */

import address from "@/assets/data/imdf/address.json";
import interact_footprint from "@/assets/data/imdf/interact/footprint.json";
import interact_levels_floor1 from "@/assets/data/imdf/interact/levels/floor1.json";
import interact_levels_floor2 from "@/assets/data/imdf/interact/levels/floor2.json";
import interact_units_floor1 from "@/assets/data/imdf/interact/units/floor1.json";
import interact_units_floor2 from "@/assets/data/imdf/interact/units/floor2.json";
import interact_units_floor3 from "@/assets/data/imdf/interact/units/floor3.json";
import studyhall_footprint from "@/assets/data/imdf/studyhall/footprint.json";
import studyhall_levels_floor1_3 from "@/assets/data/imdf/studyhall/levels/floor1$3.json";
import studyhall_levels_floor4_5 from "@/assets/data/imdf/studyhall/levels/floor4$5.json";
import studyhall_sections_floor1 from "@/assets/data/imdf/studyhall/sections/floor1.json";
import studyhall_sections_floor2 from "@/assets/data/imdf/studyhall/sections/floor2.json";
import studyhall_sections_floor3 from "@/assets/data/imdf/studyhall/sections/floor3.json";
import studyhall_sections_floor4 from "@/assets/data/imdf/studyhall/sections/floor4.json";
import studyhall_sections_floor5 from "@/assets/data/imdf/studyhall/sections/floor5.json";
import studyhall_stairs from "@/assets/data/imdf/studyhall/stairs.json";
import studyhall_units_floor1 from "@/assets/data/imdf/studyhall/units/floor1.json";
import studyhall_units_floor2 from "@/assets/data/imdf/studyhall/units/floor2.json";
import studyhall_units_floor3 from "@/assets/data/imdf/studyhall/units/floor3.json";
import studyhall_units_floor4 from "@/assets/data/imdf/studyhall/units/floor4.json";
import studyhall_units_floor5 from "@/assets/data/imdf/studyhall/units/floor5.json";
import venue_venue from "@/assets/data/imdf/venue/venue.json";

export const geoJsonMap = {
  address: {
    logicalId: "address",
    relativePath: "address.json",
    content: address,
  },
  interact_footprint: {
    logicalId: "interact_footprint",
    relativePath: "interact/footprint.json",
    content: interact_footprint,
  },
  interact_levels_floor1: {
    logicalId: "interact_levels_floor1",
    relativePath: "interact/levels/floor1.json",
    content: interact_levels_floor1,
  },
  interact_levels_floor2: {
    logicalId: "interact_levels_floor2",
    relativePath: "interact/levels/floor2.json",
    content: interact_levels_floor2,
  },
  interact_units_floor1: {
    logicalId: "interact_units_floor1",
    relativePath: "interact/units/floor1.json",
    content: interact_units_floor1,
  },
  interact_units_floor2: {
    logicalId: "interact_units_floor2",
    relativePath: "interact/units/floor2.json",
    content: interact_units_floor2,
  },
  interact_units_floor3: {
    logicalId: "interact_units_floor3",
    relativePath: "interact/units/floor3.json",
    content: interact_units_floor3,
  },
  studyhall_footprint: {
    logicalId: "studyhall_footprint",
    relativePath: "studyhall/footprint.json",
    content: studyhall_footprint,
  },
  studyhall_levels_floor1$3: {
    logicalId: "studyhall_levels_floor1$3",
    relativePath: "studyhall/levels/floor1$3.json",
    content: studyhall_levels_floor1_3,
  },
  studyhall_levels_floor4$5: {
    logicalId: "studyhall_levels_floor4$5",
    relativePath: "studyhall/levels/floor4$5.json",
    content: studyhall_levels_floor4_5,
  },
  studyhall_sections_floor1: {
    logicalId: "studyhall_sections_floor1",
    relativePath: "studyhall/sections/floor1.json",
    content: studyhall_sections_floor1,
  },
  studyhall_sections_floor2: {
    logicalId: "studyhall_sections_floor2",
    relativePath: "studyhall/sections/floor2.json",
    content: studyhall_sections_floor2,
  },
  studyhall_sections_floor3: {
    logicalId: "studyhall_sections_floor3",
    relativePath: "studyhall/sections/floor3.json",
    content: studyhall_sections_floor3,
  },
  studyhall_sections_floor4: {
    logicalId: "studyhall_sections_floor4",
    relativePath: "studyhall/sections/floor4.json",
    content: studyhall_sections_floor4,
  },
  studyhall_sections_floor5: {
    logicalId: "studyhall_sections_floor5",
    relativePath: "studyhall/sections/floor5.json",
    content: studyhall_sections_floor5,
  },
  studyhall_stairs: {
    logicalId: "studyhall_stairs",
    relativePath: "studyhall/stairs.json",
    content: studyhall_stairs,
  },
  studyhall_units_floor1: {
    logicalId: "studyhall_units_floor1",
    relativePath: "studyhall/units/floor1.json",
    content: studyhall_units_floor1,
  },
  studyhall_units_floor2: {
    logicalId: "studyhall_units_floor2",
    relativePath: "studyhall/units/floor2.json",
    content: studyhall_units_floor2,
  },
  studyhall_units_floor3: {
    logicalId: "studyhall_units_floor3",
    relativePath: "studyhall/units/floor3.json",
    content: studyhall_units_floor3,
  },
  studyhall_units_floor4: {
    logicalId: "studyhall_units_floor4",
    relativePath: "studyhall/units/floor4.json",
    content: studyhall_units_floor4,
  },
  studyhall_units_floor5: {
    logicalId: "studyhall_units_floor5",
    relativePath: "studyhall/units/floor5.json",
    content: studyhall_units_floor5,
  },
  venue_venue: {
    logicalId: "venue_venue",
    relativePath: "venue/venue.json",
    content: venue_venue,
  },
};

export default geoJsonMap;