#!/usr/bin/env ts-node
/**
 * generate-geojson-registry.ts
 *
 * buildManifest.json を読み、geojson を静的 import する registry ts を生成する。
 *
 * usage:
 *  npx ts-node --transpile-only ./tools/generate-geojson-registry.ts
 *  npx ts-node --transpile-only ./tools/generate-geojson-registry.ts ./assets/imdf/buildManifest.json ./src/domain/imdf/geojsonRegistry.ts
 *
 * 注意:
 * - 出力先ファイルを上書きするので注意してね。
 * - import パスはプロジェクトのエイリアス "@/assets/imdf/" を前提にしている（必要なら調整して）。
 */

import fs from "fs";
import path from "path";

const [, , typeImportArg] = process.argv;

const manifestPath = path.resolve("../assets/imdf/buildManifest.json");
const outPath = path.resolve("../src/Appinit/loadGeoJson/geojsonRegistry.ts");
// 型定義 import パス（生成ファイル内で使う相対／エイリアスパス）
const manifestTypeImport = typeImportArg || "./Manifest/manifestType";

function toPosix(p: string) {
  return p.split(path.sep).join("/");
}

function makeIdentifier(base: string) {
  // logicalId が安全ならそれをベースに、そうでなければ normalize する
  let id = base.replace(/[^a-zA-Z0-9_]/g, "_");
  if (!/^[a-zA-Z_]/.test(id)) id = "_" + id;
  return `data_${id}`;
}

function readManifest(p: string) {
  if (!fs.existsSync(p)) throw new Error(`manifest not found: ${p}`);
  const raw = fs.readFileSync(p, "utf8");
  return JSON.parse(raw);
}

function validIdentifier(s: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
}

function generate(manifest: any) {
  if (!manifest.files || typeof manifest.files !== "object") {
    throw new Error("manifest.files is not found or invalid");
  }

  const entries = Object.entries(manifest.files) as [string, any][];
  const imports: string[] = [];
  const mapEntries: string[] = [];
  const usedNames = new Set<string>();

  for (const [logicalId, meta] of entries) {
    const relPath: string = meta.relativePath;
    if (!relPath) {
      console.warn(`skip ${logicalId}: no relativePath`);
      continue;
    }

    // import path: assume assets are under "@/assets/imdf/"
    const importPath = `@/assets/imdf/${toPosix(relPath)}`;

    // var name
    let varName = makeIdentifier(logicalId);
    // ensure uniqueness
    let counter = 1;
    while (usedNames.has(varName)) {
      varName = `${makeIdentifier(logicalId)}_${counter}`;
      counter++;
    }
    usedNames.add(varName);

    imports.push(`import ${varName} from "${importPath}";`);

    // Prepare version/size strings
    const version = typeof meta.version === "string" ? meta.version : "";
    const size =
      typeof meta.size === "number"
        ? meta.size
        : meta.size
          ? Number(meta.size)
          : 0;

    // Use unquoted key if logicalId is a valid identifier, otherwise quote it
    const key = validIdentifier(logicalId)
      ? logicalId
      : JSON.stringify(logicalId);

    mapEntries.push(
      `  ${key}: {
    logicalId: ${JSON.stringify(logicalId)},
    relativePath: ${JSON.stringify(relPath)},
    version: ${JSON.stringify(version)},
    size: ${size},
    content: ${varName},
  },`,
    );
  }

  const header = `/* THIS FILE IS AUTO-GENERATED BY tools/generate-geojson-registry.ts */
/* Do not edit by hand. */\n`;

  const body = [
    header,
    `import { ManifestFileEnrty } from "${manifestTypeImport}";`,
    ...imports,
    "",
    `export const geoJsonMap: Record<string, ManifestFileEnrty & { content?: any }> = {`,
    ...mapEntries,
    `};`,
    "",
    `export default geoJsonMap;`,
  ].join("\n");

  return body;
}

export function generateGeojsonRegistry() {
  try {
    const manifest = readManifest(manifestPath);
    const out = generate(manifest);
    // Ensure directory exists
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, out, "utf8");
    console.log("Wrote registry to", outPath);
  } catch (e: any) {
    console.error(e.message || e);
    process.exit(1);
  }
}
